name: my-project
build-path: .build

# bins:
  # aapt2: bin/aapt2
  # javac: bin/javac
  # jar: bin/jar
  # jarsigner: bin/jarsigner
  # d8: bin/d8
  # zip: bin/zip
  # zipalign: bin/zipalign

android:
  sdk-api-version: 29
  sdk-min-api-version: 24

  # sdk-path: env(ANDROID_SDK)
  manifest-path: AndroidManifest.xml
  res-path: src/res
  java-path: src/java

  keystore-path: myproject.keystore
  keystore-alias: myproject
  keystore-store-pass: 87654321
  keystore-key-pass: 87654321

dependencies:
  - androidx.constraintlayout:constraintlayout:2.2.0
  - md3.hehe:mrje:2.2.0
  - java.ejhej:mrje:8.0.2
